" Print friendly ASCII-art cat whenever I open Vim. (Not working for some reason)
"echo ">^.^<"

" Turn on relative line numbers.
set number relativenumber

" Set leader and local leader.
let mapleader = " "
let maplocalleader = "\\"

" Mappings for moving the current line down or up.
nnoremap <leader>- ddp
nnoremap <leader>_ ddkP

" Mappings for uppercasing the current word in insert and normal modes.
inoremap <c-u> <esc>viwUea
nnoremap <leader><c-u> viwU

" Mappings to open and source vimrc file.
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Mappings for surrounding the current word (or selection) with quotes.
nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>bi'<esc>lel
vnoremap <leader>" <esc>`>a"<esc>`<i"<esc>lel
vnoremap <leader>' <esc>`>a'<esc>`<i'<esc>lel

" Mappings for going to the beginning and end of the line. (Not sure yet if I
" like these enough to give up the original functions of H and L)
nnoremap H 0
nnoremap L $

" Abbreviation for email address.
iabbrev @@ myemail@example.com
